apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../crds/common
- ../dependencies
- ../monitoring
- ../operator
- ../scorecard
- ../samples

images:
- name: observability-operator
  newName: observability-operator
  newTag: 0.0.24

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: NOT-USED-BECAUSE-TARGET-IS-SPECIFIED
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
                weight: 1
  target:
    group: apps
    kind: Deployment
    version: v1
