apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
    app.kubernetes.io/part-of: observability-operator
    app.kubernetes.io/version: 0.59.1-rhobs4
  name: observability-operator-prometheus-operator-admission-webhook
spec:
  endpoints:
  - honorLabels: true
    port: https
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator-admission-webhook
      app.kubernetes.io/version: 0.59.1-rhobs4
