kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  # 10.96.223.192 is the fixed ip of the registry service - see: hack/kind/registry.yaml
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."local-registry:30000"]
      endpoint = ["http://10.96.223.192:30000"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
      # operator metrics endpoint for scrapping with promq
      - containerPort: 30001
        hostPort: 30001
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          # enable auditing flags on the API server
          extraArgs:
            audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
            audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
          # mount new files / directories on the control plane
          extraVolumes:
            - name: audit-policies
              hostPath: /etc/kubernetes/policies
              mountPath: /etc/kubernetes/policies
              readOnly: true
              pathType: "DirectoryOrCreate"
            - name: "audit-logs"
              hostPath: "/var/log/kubernetes"
              mountPath: "/var/log/kubernetes"
              readOnly: false
              pathType: DirectoryOrCreate
    # mount the local file on the control plane
    extraMounts:
      - hostPath: ./hack/kind/audit-policy.yaml
        containerPath: /etc/kubernetes/policies/audit-policy.yaml
        readOnly: true