apiVersion: v1
kind: Service
metadata:
  name: operator-metrics-service
  labels:
    app: operator-metrics
spec:
  # NOTE: 30001 must be exposed: see hack/kind/config.yaml
  type: NodePort
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 8080
      nodePort: 30001
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: observability-operator
