apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: federate-cmo-ms
  namespace: federate-cmo
spec:
  resourceSelector: 
    matchLabels:
      monitoring.rhobs/stack: federate-cmo-ms

  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: openshift-monitoring

  logLevel: debug
  retention: 3h
  alertmanagerConfig:
    disabled: true
  prometheusConfig:
    replicas: 1
    enableRemoteWriteReceiver: true

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
