
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-stack-operator
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - monitoring-stack-operator
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: monitoring-stack-operator
  namespace: monitoring-stack-operator
rules:
- apiGroups:
  - integreatly.org
  resources:
  - grafanadatasources
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - grafanas
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - subscriptions
  verbs:
  - create
  - list
  - update
  - watch
