---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-operator
subjects:
- kind: ServiceAccount
  name: observability-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observability-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observability-operator
subjects:
  - kind: ServiceAccount
    name: observability-operator-sa
    namespace: default
