---
# NOTE: For PrometheusRule ObO uses platform monitoring in OpenShift
# instead of the forked PO's CRDs. As the ObO bundle ships the forked PO's CRD,
# these won't be available at the time OLM installs the bundle
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/part-of: observability-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: observability-operator
      app.kubernetes.io/component: operator
  endpoints:
  - port: metrics
