---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-operator
  labels:
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: observability-operator
      app.kubernetes.io/component: operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: observability-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/version: 0.0.1
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: operator
          image: observability-operator:0.0.1
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=$(NAMESPACE)
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 150Mi
      serviceAccountName: observability-operator-sa
      terminationGracePeriodSeconds: 30
