resources:
# CRDs
- https://raw.githubusercontent.com/sthaha/prometheus-operator/v0.58.0-rhobs2/example/stripped-down-crds/all.yaml

# PO Deployment
- https://raw.githubusercontent.com/sthaha/prometheus-operator/v0.58.0-rhobs2/example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
- https://raw.githubusercontent.com/sthaha/prometheus-operator/v0.58.0-rhobs2/example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
- https://raw.githubusercontent.com/sthaha/prometheus-operator/v0.58.0-rhobs2/example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- https://raw.githubusercontent.com/sthaha/prometheus-operator/v0.58.0-rhobs2/example/rbac/prometheus-operator/prometheus-operator-service-account.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operators
namePrefix: observability-operator-
commonLabels:
  app.kubernetes.io/part-of: observability-operator

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prometheus-operator
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/part-of: observability-operator
        template:
          metadata:
            annotations:
              target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
            labels:
              app.kubernetes.io/part-of: observability-operator
          spec:
            containers:
              - name: prometheus-operator
                image: quay.io/sthaha/rhobs-prometheus-operator:v0.58.0-rhobs2
                args:
                  - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.58.0
                  - --prometheus-instance-selector=app.kubernetes.io/managed-by=observability-operator
                  - --alertmanager-instance-selector=app.kubernetes.io/managed-by=observability-operator
                  - --thanos-ruler-instance-selector=app.kubernetes.io/managed-by=observability-operator
                resources:
                  requests:
                    cpu: 5m
                    memory: 150Mi
                  limits:
                    cpu: 100m
                    memory: 500Mi
                terminationMessagePolicy: FallbackToLogsOnError
            securityContext:
              runAsNonRoot: true
  - patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector
    target:
      group: apps
      version: v1
      kind: Deployment

  - patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - security.openshift.io
          resourceNames:
            - nonroot-v2
            - nonroot
          resources:
            - securitycontextconstraints
          verbs:
            - use
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: prometheus-operator
