name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.16

    - name: Build
      run: make build
    - name: Test
      run: make test
    
    - name: Build Operator
      run: make docker-build IMG=quay.io/sthaha/monitoring-stack-operator:v0.0.1
    
    
