---
name: Makefile CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: quay

    steps:

      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16

      - name: Build
        run: make build
      - name: Test
        run: make test

      - name: Build Operator Image
        run: make docker-build IMG=quay.io/sthaha/monitoring-stack-operator:v0.0.1

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@v1.10.0
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: quay.io
          # Username used to log against the Docker registry
          username: ${{ secrets.QUAY_LOGIN }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Publish Operator
        run: make docker-push IMG=quay.io/sthaha/monitoring-stack-operator:v0.0.1
