---
name: OLM Stable Channel

on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: ubuntu-latest
    environment: quay
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      - name: publish
        uses: ./.github/olm-publish
        env:
          IMAGE_BASE: ${{ secrets.IMAGE_BASE }}
          CHANNELS: stable,candidate,development
          DEFAULT_CHANNEL: stable
        with:
          quay_login: ${{ secrets.QUAY_LOGIN }}
          quay_token: ${{ secrets.QUAY_TOKEN }}
          go-version: ${{ env.go-version }}
