---
name: OLM Candidate Channel

on:
  release:
    types:
      - prereleased

jobs:
  release:
    runs-on: ubuntu-latest
    environment: quay
    steps:
      - uses: actions/checkout@v2

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      - name: Set version
        id: version
        run: |
          version="$(cat VERSION)-rc"
          echo "::set-output name=version::$version"

      - name: publish
        uses: ./.github/olm-publish
        env:
          IMAGE_BASE: ${{ secrets.IMAGE_BASE }}
          VERSION: ${{ steps.version.outputs.version }}
          CHANNELS: candidate,development
          DEFAULT_CHANNEL: candidate
        with:
          quay_login: ${{ secrets.QUAY_LOGIN }}
          quay_token: ${{ secrets.QUAY_TOKEN }}
          go-version: ${{ env.go-version }}

      - name: Publish tag
        id: publish_tag
        run: |
          git config user.name rhobs-release-bot
          git config user.email release-bot@monitoring.rhobs.io
          git tag -a "$(cat VERSION)" -m "$(cat VERSION) release candidate"
          git push --follow-tags
