---
name: OLM Candidate Channel

on:
  release:
    types:
      - prereleased

jobs:
  release:
    runs-on: ubuntu-latest
    environment: quay
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.REPOSITORY_PUSH_TOKEN }}

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      - name: Set version
        id: version
        run: |
          version="$(cat VERSION)-rc"
          echo "::set-output name=version::$version"

      - name: publish catalog
        uses: ./.github/olm-publish
        env:
          IMAGE_BASE: ${{ secrets.IMAGE_BASE }}
          VERSION: ${{ steps.version.outputs.version }}
          CHANNELS: candidate,development
          DEFAULT_CHANNEL: candidate
        with:
          quay_login: ${{ secrets.QUAY_LOGIN }}
          quay_token: ${{ secrets.QUAY_TOKEN }}
          go-version: ${{ env.go-version }}

      - name: Create git release tag
        run: |
          git config user.name rhobs-release-bot
          git config user.email release-bot@monitoring.rhobs.io
          git tag -a "$(cat VERSION)" -m "$(cat VERSION) release candidate"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPOSITORY_PUSH_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
