# Decide between Pre-Release and Development Release
name: release
on:
  push:
    branches: [main]

jobs:
  e2e-tests-olm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      - name: e2e tests through OLM
        uses: ./.github/e2e-tests-olm
        with:
          go-version: ${{ env.go-version }}

  publish-olm-development:
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    environment: quay
    needs:
      - e2e-tests-olm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      # Bumping the version in the next step will also run code generation scripts
      # that depend on controller-gen.
      # Therefore, we first need to setup Go so that we can install the
      # controller-gen binary.
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Set version
        id: version
        run: |
          npx standard-version --skip.commit --skip.tag --skip.changelog
          version="$(cat VERSION)-$(date +%y%m%d%H%M%S)"
          echo "::set-output name=version::$version"

      - name: Publish
        uses: ./.github/olm-publish
        env:
          IMAGE_BASE: ${{ secrets.IMAGE_BASE }}
          VERSION: ${{ steps.version.outputs.version }}
          CHANNELS: development
        with:
          quay_login: ${{ secrets.QUAY_LOGIN }}
          quay_token: ${{ secrets.QUAY_TOKEN }}

      - name: Push catalog index changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPOSITORY_PUSH_TOKEN }}
          branch: olm-catalog

  create-github-prerelease:
    needs:
      - e2e-tests-olm
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.REPOSITORY_PUSH_TOKEN }}

      - name: Import common environment variables
        run: cat ".github/env" >> $GITHUB_ENV

      # Bumping the version in the next step will also run code generation scripts
      # that depend on controller-gen.
      # Therefore, we first need to setup Go so that we can install the
      # controller-gen binary.
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ env.go-version }}

      - name: Generate release notes
        run: |
          # Create the release notes for the Github release
          git config user.name rhobs-release-bot
          git config user.email release-bot@monitoring.rhobs.io
          npx standard-version -i RELEASE_BODY.md  \
            --release-as $(cat VERSION) \
            --skip.commit

      - name: Publish tag
        id: publish_tag
        run: |
          # NOTE tag is created by standard-version and points to the
          # chore(release): commit as opposed to pointing to the commit added
          # to olm-catalog branch after images are built and pushed
          git push --follow-tags
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)

      - name: Create Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_PUSH_TOKEN }}
        with:
          release_name: ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: RELEASE_BODY.md
          # NOTE: We always generate pre-releases and mark them as releases manually
          prerelease: true
